### ISSUE TITLE
reasoning fails using HermiT

### ISSUE THREAD

**Issue by wdduncan** [CIDO-ontology/cido#25]
When you run the HermiT reasoner it fails with error message:
```
ERROR  22:12:23  An error occurred during reasoning: The given property hierarchy is not regular.
There is a cyclic dependency involving property BFO_0000050.
java.lang.IllegalArgumentException: The given property hierarchy is not regular.
There is a cyclic dependency involving property BFO_0000050
	at org.semanticweb.HermiT.structural.ObjectPropertyInclusionManager.checkForRegularity(ObjectPropertyInclusionManager.java:665) ~[na:na]
	at org.semanticweb.HermiT.structural.ObjectPropertyInclusionManager.createAutomata(ObjectPropertyInclusionManager.java:196) ~[na:na]
	at org.semanticweb.HermiT.structural.ObjectPropertyInclusionManager.<init>(ObjectPropertyInclusionManager.java:58) ~[na:na]
	at org.semanticweb.HermiT.structural.OWLClausification.preprocessAndClausify(OWLClausification.java:156) ~[na:na]
	at org.semanticweb.HermiT.Reasoner.loadOntology(Reasoner.java:211) ~[na:na]
	at org.semanticweb.HermiT.Reasoner.<init>(Reasoner.java:202) ~[na:na]
	at org.semanticweb.HermiT.Reasoner.<init>(Reasoner.java:176) ~[na:na]
	at org.semanticweb.HermiT.ReasonerFactory.createHermiTOWLReasoner(ReasonerFactory.java:51) ~[na:na]
	at org.semanticweb.HermiT.ReasonerFactory.createReasoner(ReasonerFactory.java:19) ~[na:na]
	at org.protege.editor.owl.model.inference.ReasonerUtilities.createReasoner(ReasonerUtilities.java:20) ~[na:na]
	at org.protege.editor.owl.model.inference.OWLReasonerManagerImpl$ClassificationRunner.ensureRunningReasonerInitialized(OWLReasonerManagerImpl.java:428) ~[na:na]
	at org.protege.editor.owl.model.inference.OWLReasonerManagerImpl$ClassificationRunner.run(OWLReasonerManagerImpl.java:386) ~[na:na]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_121]
```

**Comment by yongqunh** [comment]
BFO_0000050 is part_of. Debugging is needed. Thanks!

**Comment by yongqunh** [comment]
When I use ELK as the reasoner, this issue does not occur.
 
A proper reason is that the part_of (BFO_0000050) is transitive, which may eventually form cyclic dependency. However, when I do not make it transitive, the issue appears still there. Any suggestion?

**Comment by wdduncan** [comment]
Not sure what the best way to debug this is. We need to look at the use of `part of` and see if we can spot the cycle. I wonder if there is a tool we can use.

**Comment by wdduncan** [comment]
@yongqunh I've created a new branch for this issue (cf. branch `issue-25`).

On my local machine, I've created an error report about CIDO's compliance with the DL profile using the command:
```
robot validate-profile -p DL -i cido.owl > cido-errors.txt
```
Next, to find the cyclic error, I ran the command `grep BFO_0000050 cido-errors.txt `; output:
```
Use of property in chain causes cycle: <http://purl.obolibrary.org/obo/BFO_0000050> [SubObjectPropertyOf(ObjectPropertyChain( <http://purl.obolibrary.org/obo/BFO_0000050> <http://purl.obolibrary.org/obo/RO_0002202> ) <http://purl.obolibrary.org/obo/RO_0002202>) in OntologyID(OntologyIRI(<http://purl.obolibrary.org/obo/cido.owl>) VersionIRI(<null>))]
```
Looking at the ontology, I see that `develops_from` (with the underscore) is a child of `part of`. This is not how it is represented in the relations ontology. I will experiment with editing this portion of the ontology.

There are number of other errors in `cido-errors.txt`. You may be interested in running this command too in order to see the rest of the errors.

**Comment by wdduncan** [comment]
See PR https://github.com/CIDO-ontology/cido/pull/33.

This fixes the error but we need to determine if the object property chains need to be reimplemented. My intuition tells me "no". ELK doesn't compute property chains, and this is the reasoner that was being used.

**Comment by yongqunh** [comment]
Hi Bill,

This looks great. Thanks!

Oliver
